jobs:
  - name: u16python-test
    type: runSh
    steps:
      - IN: u14all-testing
      - TASK:
          runtime:
            options:
              imageName: "drydock/u16pytall"
              imageTag: master
          script:
             - python --version
             - python2.3 -V
             - python2.4 -V
             - python2.5 -V
             - python2.6 -V
             - python2.7 -V
             - python3.1 -V
             - python3.2 -V
             - python3.4 -V
             - python3.5 -V
             - python3.6 -V
             - python3.7 -V
             - pip --version
